---
 
 - name: do autoremove
   shell: 'apt-get -y autoremove'
   register: autoremove_output
   changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"

 - name: do purge
   script: dpkg-rc.sh
   register: purge_output
   changed_when: purge_output.rc == 16
